development:
  username: bitcoin-admin
  password: password
  url: http://localhost:8332/
  donations: 1FXWhKPChEcUnSEoFQ3DGzxKe44MDbatz
  
test:
  username: bitcoin-admin
  password: password
  url: http://localhost:8332/
  donations: 1FXWhKPChEcUnSEoFQ3DGzxKe44MDbatz
